### ISSUE TITLE
Compile fails on with recent gupnp-1.4.2 (Workaround inside)

### ISSUE THREAD

**Issue by lfinbob** [phako/korva#7]
Compiling the latest git code fails on an up to date gentoo system with gupnp-1.4.2

> ~/build-2022-new-checkout/build # meson compile
> [6/24] Compiling C object client/korva-control.p/korva-control.c.o
> FAILED: client/korva-control.p/korva-control.c.o 
> cc -Iclient/korva-control.p -Iclient -I../client -I. -I.. -Idbus -I../dbus -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/libmount -I/usr/include/blkid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -pthread -DHAVE_CONFIG_H -MD -MQ client/korva-control.p/korva-control.c.o -MF client/korva-control.p/korva-control.c.o.d -o client/korva-control.p/korva-control.c.o -c ../client/korva-control.c
> ../client/korva-control.c:30:10: fatal error: korva-dbus-interface.h: No such file or directory
>    30 | #include <korva-dbus-interface.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> [15/24] Compiling C object server/upnp/libkorva-upnp-backend.a.p/korva-upnp-device.c.o
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_introspect_renderer':
> ../server/upnp/korva-upnp-device.c:503:5: warning: 'gupnp_service_proxy_begin_action' is deprecated [-Wdeprecated-declarations]
>   503 |     gupnp_service_proxy_begin_action (proxy,
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:103:1: note: declared here
>   103 | gupnp_service_proxy_begin_action   (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_on_get_transport_info':
> ../server/upnp/korva-upnp-device.c:520:5: warning: 'gupnp_service_proxy_end_action' is deprecated [-Wdeprecated-declarations]
>   520 |     gupnp_service_proxy_end_action (proxy,
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:127:1: note: declared here
>   127 | gupnp_service_proxy_end_action     (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c:543:5: warning: 'gupnp_service_proxy_begin_action' is deprecated [-Wdeprecated-declarations]
>   543 |     gupnp_service_proxy_begin_action (cm_proxy,
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:103:1: note: declared here
>   103 | gupnp_service_proxy_begin_action   (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_on_get_protocol_info':
> ../server/upnp/korva-upnp-device.c:561:5: warning: 'gupnp_service_proxy_end_action' is deprecated [-Wdeprecated-declarations]
>   561 |     gupnp_service_proxy_end_action (proxy,
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:127:1: note: declared here
>   127 | gupnp_service_proxy_end_action     (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_on_play':
> ../server/upnp/korva-upnp-device.c:844:5: warning: 'gupnp_service_proxy_end_action' is deprecated [-Wdeprecated-declarations]
>   844 |     gupnp_service_proxy_end_action (proxy, action, &error, NULL);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:127:1: note: declared here
>   127 | gupnp_service_proxy_end_action     (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_on_stop':
> ../server/upnp/korva-upnp-device.c:877:5: warning: 'gupnp_service_proxy_end_action' is deprecated [-Wdeprecated-declarations]
>   877 |     gupnp_service_proxy_end_action (proxy, action, &error, NULL);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:127:1: note: declared here
>   127 | gupnp_service_proxy_end_action     (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c:889:9: warning: 'gupnp_service_proxy_begin_action' is deprecated [-Wdeprecated-declarations]
>   889 |         gupnp_service_proxy_begin_action (proxy,
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:103:1: note: declared here
>   103 | gupnp_service_proxy_begin_action   (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_on_set_av_transport_uri':
> ../server/upnp/korva-upnp-device.c:915:5: warning: 'gupnp_service_proxy_end_action' is deprecated [-Wdeprecated-declarations]
>   915 |     gupnp_service_proxy_end_action (proxy, action, &error, NULL);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:127:1: note: declared here
>   127 | gupnp_service_proxy_end_action     (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c:921:13: warning: 'gupnp_service_proxy_begin_action' is deprecated [-Wdeprecated-declarations]
>   921 |             gupnp_service_proxy_begin_action (proxy,
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:103:1: note: declared here
>   103 | gupnp_service_proxy_begin_action   (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c:958:9: warning: 'gupnp_service_proxy_begin_action' is deprecated [-Wdeprecated-declarations]
>   958 |         gupnp_service_proxy_begin_action (proxy,
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:103:1: note: declared here
>   103 | gupnp_service_proxy_begin_action   (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_on_host_file_async':
> ../server/upnp/korva-upnp-device.c:1074:5: warning: 'gupnp_service_proxy_begin_action' is deprecated [-Wdeprecated-declarations]
>  1074 |     gupnp_service_proxy_begin_action (proxy,
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:103:1: note: declared here
>   103 | gupnp_service_proxy_begin_action   (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../server/upnp/korva-upnp-device.c: In function 'korva_upnp_device_unshare_async':
> ../server/upnp/korva-upnp-device.c:1240:5: warning: 'gupnp_service_proxy_begin_action' is deprecated [-Wdeprecated-declarations]
>  1240 |     gupnp_service_proxy_begin_action (proxy,
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp-control-point.h:17,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp-context-manager.h:16,
>                  from /usr/include/gupnp-1.2/libgupnp/gupnp.h:11,
>                  from ../server/upnp/korva-upnp-device.h:26,
>                  from ../server/upnp/korva-upnp-device.c:29:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service-proxy.h:103:1: note: declared here
>   103 | gupnp_service_proxy_begin_action   (GUPnPServiceProxy              *proxy,
>       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [17/24] Compiling C object tests/test-upnp.p/mock-dmr_mock-dmr.c.o
> ../tests/mock-dmr/mock-dmr.c: In function 'on_get_protocol_info':
> ../tests/mock-dmr/mock-dmr.c:169:9: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   169 |         gupnp_service_action_return (action);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp.h:23,
>                  from ../tests/mock-dmr/mock-dmr.h:26,
>                  from ../tests/mock-dmr/mock-dmr.c:25:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service.h:110:6: note: declared here
>   110 | void gupnp_service_action_return (GUPnPServiceAction *action);
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../tests/mock-dmr/mock-dmr.c:186:5: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   186 |     gupnp_service_action_return (action);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp.h:23,
>                  from ../tests/mock-dmr/mock-dmr.h:26,
>                  from ../tests/mock-dmr/mock-dmr.c:25:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service.h:110:6: note: declared here
>   110 | void gupnp_service_action_return (GUPnPServiceAction *action);
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../tests/mock-dmr/mock-dmr.c: In function 'on_play':
> ../tests/mock-dmr/mock-dmr.c:197:9: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   197 |         gupnp_service_action_return (action);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp.h:23,
>                  from ../tests/mock-dmr/mock-dmr.h:26,
>                  from ../tests/mock-dmr/mock-dmr.c:25:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service.h:110:6: note: declared here
>   110 | void gupnp_service_action_return (GUPnPServiceAction *action);
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../tests/mock-dmr/mock-dmr.c: In function 'on_stop':
> ../tests/mock-dmr/mock-dmr.c:209:9: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   209 |         gupnp_service_action_return (action);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp.h:23,
>                  from ../tests/mock-dmr/mock-dmr.h:26,
>                  from ../tests/mock-dmr/mock-dmr.c:25:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service.h:110:6: note: declared here
>   110 | void gupnp_service_action_return (GUPnPServiceAction *action);
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../tests/mock-dmr/mock-dmr.c: In function 'on_pause':
> ../tests/mock-dmr/mock-dmr.c:218:5: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   218 |     gupnp_service_action_return (action);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp.h:23,
>                  from ../tests/mock-dmr/mock-dmr.h:26,
>                  from ../tests/mock-dmr/mock-dmr.c:25:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service.h:110:6: note: declared here
>   110 | void gupnp_service_action_return (GUPnPServiceAction *action);
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../tests/mock-dmr/mock-dmr.c: In function 'on_get_transport_info':
> ../tests/mock-dmr/mock-dmr.c:249:5: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   249 |     gupnp_service_action_return (action);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp.h:23,
>                  from ../tests/mock-dmr/mock-dmr.h:26,
>                  from ../tests/mock-dmr/mock-dmr.c:25:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service.h:110:6: note: declared here
>   110 | void gupnp_service_action_return (GUPnPServiceAction *action);
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../tests/mock-dmr/mock-dmr.c: In function 'on_set_av_transport_uri':
> ../tests/mock-dmr/mock-dmr.c:298:5: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   298 |     gupnp_service_action_return (action);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/gupnp-1.2/libgupnp/gupnp.h:23,
>                  from ../tests/mock-dmr/mock-dmr.h:26,
>                  from ../tests/mock-dmr/mock-dmr.c:25:
> /usr/include/gupnp-1.2/libgupnp/gupnp-service.h:110:6: note: declared here
>   110 | void gupnp_service_action_return (GUPnPServiceAction *action);
>       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> [18/24] Compiling C object tests/test-upnp.p/test-upnp.c.o
> ninja: build stopped: subcommand failed.

Found this quick hack/workaround:
`cp build/dbus/korva-dbus-interface.h {client,server}/`

**Comment by phako** [comment]
I think this is more of a recent change in meson

**Comment by phako** [comment]
Whats your meson version, this seems to work fine here with 0.59.4

**Comment by lfinbob** [comment]
I'm using meson-0.60.3, which is the latest stable version on gentoo.

**Comment by phako** [comment]
hm. just tried with 0.60.3, also works fine here. Very weird.

**Comment by lfinbob** [comment]
Not sure what the problem is then. Maybe the ninja version? I use 1.10.2-r1.

Here are the commands I used:

>   wget https://github.com/phako/korva/archive/refs/heads/master.zip
>   unzip master.zip 
>   mv korva-master/* .
>   rm -fr korva-master/
>   mkdir build
>   cd build
>   meson ..
>   meson compile

**Comment by phako** [comment]
1.10.2 here as well. I did your above steps and it works. very curious. If you do ninja -v , does the build directory show up as an include directory  (-I ...) for you?

**Comment by lfinbob** [comment]
No, it does not:

> majestix /usr/local/bin/korva_upnp_eg37_tv/build-2022-new-checkout/build # ninja -v
> [1/2] cc  -o tests/test-upnp tests/test-upnp.p/mock-dmr_mock-dmr.c.o tests/test-upnp.p/test-upnp.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group server/upnp/libkorva-upnp-backend.a server/libkorva-core.a /usr/lib64/libxml2.so /usr/lib64/libgobject-2.0.so /usr/lib64/libglib-2.0.so /usr/lib64/libgupnp-1.2.so /usr/lib64/libgssdp-1.2.so /usr/lib64/libgio-2.0.so /usr/lib64/libsoup-2.4.so -Wl,--export-dynamic /usr/lib64/libgmodule-2.0.so -pthread /usr/lib64/libgupnp-av-1.0.so -Wl,--end-group
> [2/2] cc  -o server/korva-server server/korva-server.p/korva-server.c.o server/korva-server.p/korva.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group server/libkorva-core.a dbus/libkorva-dbus.a server/upnp/libkorva-upnp-backend.a /usr/lib64/libglib-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libgio-2.0.so /usr/lib64/libgupnp-1.2.so /usr/lib64/libgssdp-1.2.so /usr/lib64/libsoup-2.4.so -Wl,--export-dynamic /usr/lib64/libgmodule-2.0.so -pthread /usr/lib64/libgupnp-av-1.0.so -Wl,--end-group

**Comment by phako** [comment]
That is just the linking. It should look like this:
`[17/24] ccache cc -Iclient/korva-control.p -Iclient -I../client -I. -I.. -Idbus -I../dbus -I/home/jgeorg/jhbuild/install/include/glib-2.0 -I/home/jgeorg/jhbuild/install/lib/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -pthread -DHAVE_CONFIG_H -MD -MQ client/korva-control.p/korva-control.c.o -MF client/korva-control.p/korva-control.c.o.d -o client/korva-control.p/korva-control.c.o -c ../client/korva-control.c`

the `-Idbus -I../dbus` is the iomportant part

**Comment by lfinbob** [comment]
OK, I ran `meson compile --verbose` and it seems the dbus include is indeed missing:

> 17/24] /usr/bin/xsltproc -o doc/korva-control.1 --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ../doc/man/korva-control.xml
> [18/24] cc -Itests/test-upnp.p -Itests -I../tests -Iserver/upnp -I../server/upnp -Iserver -I../server -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/gupnp-1.2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gssdp-1.2 -I/usr/include/libsoup-2.4 -I/usr/include/uuid -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -pthread '-DTEST_DATA_DIR="/usr/local/bin/korva_upnp_eg37_tv/build-2022-new-checkout/tests"' -MD -MQ tests/test-upnp.p/mock-dmr_mock-dmr.c.o -MF tests/test-upnp.p/mock-dmr_mock-dmr.c.o.d -o tests/test-upnp.p/mock-dmr_mock-dmr.c.o -c ../tests/mock-dmr/mock-dmr.c
> ../tests/mock-dmr/mock-dmr.c: In function 'on_get_protocol_info':
> ../tests/mock-dmr/mock-dmr.c:169:9: warning: 'gupnp_service_action_return' is deprecated: Use 'gupnp_service_action_return_success' instead [-Wdeprecated-declarations]
>   169 |         gupnp_service_action_return (action);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by phako** [comment]
Interestingly it has in your original report, but yet fails o.O
