### ISSUE TITLE
korva-server finds no devices with gupnp-1.4.2 (assertion 'GUPNP_IS_SERVICE_PROXY (proxy)' failed)

### ISSUE THREAD

**Issue by lfinbob** [phako/korva#8]
Upgrading to gupnp-1.4.2 on gentoo broke my script to push videos to my Samsung TV.
korva-server now yields these errors, whereas before the upgrade it worked flawlessy. Nothing changed on the TV or network.
korva-control -l lists "no devices".

> ** (process:27925): CRITICAL **: 19:24:06.015: gupnp_service_proxy_end_action: assertion 'GUPNP_IS_SERVICE_PROXY (proxy)' failed
> 
> ** (process:27925): CRITICAL **: 19:24:06.025: gupnp_service_proxy_end_action: assertion 'GUPNP_IS_SERVICE_PROXY (proxy)' failed
> 
> (process:27925): Korva-UPnP-Device-Lister-WARNING **: 19:24:06.025: Failed to add device: Device uuid:0a21fe80-00aa-1000-81f6-c4731ee2105d did not properly reply to GetProtocolInfo call

I did checkout the latest sources and recompile.

**Comment by phako** [comment]
Yeah, sorry about that, I massively screwed up the 1.4.x releases.
